services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_PREFIX:-laravel}-app
    container_name: ${APP_PREFIX:-laravel}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: ${APP_PREFIX:-laravel}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - app-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_PREFIX:-laravel}-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  app-data:
    driver: local

networks:
  app-network:
    driver: bridge 